--実行結果ログ出力オフ
set feedback off;
SET SERVEROUTPUT ON;
SET LINE 1000;

-- メタデータ取得対象オブジェクトリスト出力(csv)
-- REV.2019.03.28

DECLARE

    CURSOR GET_TABLE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'TABLE'
       AND NOT OBJECT_NAME LIKE 'SYS%' 
       AND NOT OBJECT_NAME LIKE '%$%' 
    ;  --※SYS、$除く

    CURSOR GET_INDEX IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'INDEX' 
       AND NOT OBJECT_NAME LIKE 'SYS%' 
       AND NOT OBJECT_NAME LIKE '%$%'
    ;  --※SYS、$除く

    CURSOR GET_VIEW IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'VIEW' 
       AND NOT OBJECT_NAME LIKE '%$%'
    ;  --※$除く

    CURSOR GET_PROCEDURE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'PROCEDURE'
    ;

    CURSOR GET_FUNCTION IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'FUNCTION'
    ;

    CURSOR GET_PACKAGE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'PACKAGE'
    ;

    CURSOR GET_TYPE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'TYPE' AND NOT OBJECT_NAME LIKE 'SYS%'
    ;  --※SYS除く（除かないと存在する場合エラーになる）

    CURSOR GET_TRIGGER IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'TRIGGER'
    ;

    CURSOR GET_SEQUENCE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'SEQUENCE'
    ;

    CURSOR GET_SYNONYM IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM USER_OBJECTS 
     WHERE OBJECT_TYPE = 'SYNONYM'
    ;

    CURSOR GET_DB_LINK IS 
    SELECT 'DB_LINK' AS OBJECT_TYPE,
           DB_LINK AS OBJECT_NAME
      FROM USER_DB_LINKS
    ;

    CURSOR GET_MATERIALIZED_VIEW_LOG IS 
    SELECT 'MATERIALIZED_VIEW_LOG' AS OBJECT_TYPE,
           LOG_TABLE AS OBJECT_NAME
      FROM USER_MVIEW_LOGS
    ;

BEGIN

    FOR REC IN GET_TABLE                 LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_INDEX                 LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_VIEW                  LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_PROCEDURE             LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_FUNCTION              LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_PACKAGE               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_TYPE                  LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_TRIGGER               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_SEQUENCE              LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_SYNONYM               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_DB_LINK               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_MATERIALIZED_VIEW_LOG LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;

-----------------------------------------------------------
EXCEPTION   ---エラー
-----------------------------------------------------------
    WHEN OTHERS THEN
        ROLLBACK;
        -- テキストログ出力(エラー内容)
        DBMS_OUTPUT.PUT_LINE(SQLERRM(SQLCODE));

END;
/
EXIT