--実行結果ログ出力オフ、置換変数出力オフ
set feedback off
SET VERIFY OFF
SET SERVEROUTPUT ON
SET LINE 1000

-- メタデータ取得対象オブジェクトリスト出力(csv)
-- REV.2021.04.13

DECLARE

    CURSOR GET_TABLE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'TABLE' AND OWNER = '&1'
       AND NOT OBJECT_NAME LIKE 'SYS%' 
       AND NOT OBJECT_NAME LIKE '%$%' 
    ;  --※SYS、$除く

    CURSOR GET_INDEX IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'INDEX' AND OWNER = '&1'
       AND NOT OBJECT_NAME LIKE 'SYS%' 
       AND NOT OBJECT_NAME LIKE '%$%'
    ;  --※SYS、$除く

    CURSOR GET_VIEW IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'VIEW' AND OWNER = '&1'
       AND NOT OBJECT_NAME LIKE '%$%'
    ;  --※$除く

    CURSOR GET_PROCEDURE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'PROCEDURE' AND OWNER = '&1'
    ;

    CURSOR GET_FUNCTION IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'FUNCTION' AND OWNER = '&1'
    ;

    CURSOR GET_PACKAGE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'PACKAGE' AND OWNER = '&1'
    ;

    CURSOR GET_TYPE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'TYPE' AND OWNER = '&1'
       AND NOT OBJECT_NAME LIKE 'SYS%'
    ;  --※SYS除く（除かないと存在する場合エラーになる）

    CURSOR GET_TRIGGER IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'TRIGGER' AND OWNER = '&1'
    ;

    CURSOR GET_SEQUENCE IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS
     WHERE OBJECT_TYPE = 'SEQUENCE' AND OWNER = '&1'
    ;

    CURSOR GET_SYNONYM IS 
    SELECT OBJECT_TYPE,
           OBJECT_NAME
      FROM DBA_OBJECTS 
     WHERE OBJECT_TYPE = 'SYNONYM' AND OWNER = '&1'
    ;

    CURSOR GET_DB_LINK IS 
    SELECT 'DB_LINK' AS OBJECT_TYPE,
           DB_LINK AS OBJECT_NAME
      FROM DBA_DB_LINKS 
     WHERE OWNER = '&1'
    ;  --※パブリックDB_LINKは取得されないので注意

    CURSOR GET_MATERIALIZED_VIEW_LOG IS 
    SELECT 'MATERIALIZED_VIEW_LOG' AS OBJECT_TYPE,
           LOG_TABLE AS OBJECT_NAME
      FROM DBA_MVIEW_LOGS
     WHERE LOG_OWNER = '&1'
    ;

BEGIN

    FOR REC IN GET_TABLE                 LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_INDEX                 LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_VIEW                  LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_PROCEDURE             LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_FUNCTION              LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_PACKAGE               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_TYPE                  LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_TRIGGER               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_SEQUENCE              LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_SYNONYM               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_DB_LINK               LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;
    FOR REC IN GET_MATERIALIZED_VIEW_LOG LOOP DBMS_OUTPUT.PUT_LINE(REC.OBJECT_TYPE || ',' || REC.OBJECT_NAME); END LOOP;

-----------------------------------------------------------
EXCEPTION   ---エラー
-----------------------------------------------------------
    WHEN OTHERS THEN
        ROLLBACK;
        -- テキストログ出力(エラー内容)
        DBMS_OUTPUT.PUT_LINE(SQLERRM(SQLCODE));

END;
/
EXIT